import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen bg-white text-[#121416]">
          {/* Sidebar */}
          <aside className="w-80 p-4 bg-white shadow-md border-r">
            <div className="flex flex-col gap-4">
              <h1 className="text-base font-medium">Dorakart</h1>
              <nav className="flex flex-col gap-2">
                <div className="flex items-center gap-3 px-3 py-2 rounded-xl bg-[#f1f2f4]">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24px"
                    height="24px"
                    fill="currentColor"
                    viewBox="0 0 256 256"
                  >
                    <path d="M223.68,66.15...Z" />
                  </svg>
                  <p className="text-sm font-medium">Products</p>
                </div>
                <div className="flex items-center gap-3 px-3 py-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24px"
                    height="24px"
                    fill="currentColor"
                    viewBox="0 0 256 256"
                  >
                    <path d="M72,104a8...Z" />
                  </svg>
                  <p className="text-sm font-medium">Orders</p>
                </div>
                <div className="flex items-center gap-3 px-3 py-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24px"
                    height="24px"
                    fill="currentColor"
                    viewBox="0 0 256 256"
                  >
                    <path d="M227.31,73.37...Z" />
                  </svg>
                  <p className="text-sm font-medium">Designing</p>
                </div>
                <div className="flex items-center gap-3 px-3 py-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24px"
                    height="24px"
                    fill="currentColor"
                    viewBox="0 0 256 256"
                  >
                    <path d="M214.67,72...Z" />
                  </svg>
                  <p className="text-sm font-medium">Printing</p>
                </div>
              </nav>
            </div>
          </aside>

          {/* Main Content */}
          <main className="flex-1 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
